#!/usr/bin/python3

from Foodchain import foodchain

fc = foodchain("http://127.0.0.1",'corp','ftf')

#fc.create("robel1","robel2","robel3")

#fc.view_asset("Food")
#print(dir(foodchain))

print(fc.history("334565432"))

